# Generated by Django 2.2 on 2020-06-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200610_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
        migrations.AddField(
            model_name='post',
            name='user_email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
