# Generated by Django 2.2 on 2020-06-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_post_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='display_text',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
